export const PLAYER_LOAD_SUCCESS = 'PLAYER_LOAD_SUCCESS';
export const PLAYER_LOAD_FAILURE = 'PLAYER_LOAD_FAILURE';
export const TWEET_COMPARISON_SUCCESS = 'TWEET_COMPARISON_SUCCESS';
export const TWEET_COMPARISON_FAIL = 'TWEET_COMPARISON_FAIL';
